[package]
name = "shouxtech/ui-exclusive-group"
description = ""
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "src/**", "default.project.json", "wally.toml", "wally.lock"]
exclude = ["**"]

[dependencies]
Observers = "shouxtech/observers@1.0.6"